language: node_js
node_js:
    - "lts/fermium"
cache:
  directories:
  - node_modules
install:
    - npm ci
script:
    - ganache-cli -p 7545 > /dev/null &
    - sleep 5
    - npm run migrate
    - npm run test
    - npm run coverage